/**
 * AI-Generated Code Sample with Best Practice Violations
 * 
 * Problem: Process user data and generate a summary report.
 * 
 * This code was generated by an AI assistant but violates numerous
 * JavaScript best practices and clean code principles.
 */

// BEST PRACTICE VIOLATION 1: Poor naming conventions
// Variable names are cryptic and non-descriptive
function proc(d) {  // What does 'proc' do? What is 'd'?
    // VIOLATION 2: Magic numbers without explanation
    if (d.length > 100) {
        return "too many";
    }
    
    // VIOLATION 3: Single-letter variables
    let x = [];
    let y = 0;
    let z = "";
    
    // VIOLATION 4: Unclear loop logic
    for (let i = 0; i < d.length; i++) {
        let n = d[i];
        
        // VIOLATION 5: Nested conditions without clear purpose
        if (n.a) {
            if (n.s > 50) {
                if (n.t == "premium") {
                    x.push(n);
                    y += n.s;
                }
            }
        }
        
        // VIOLATION 6: String concatenation instead of template literals
        z = z + n.name + ", ";
    }
    
    // VIOLATION 7: No error handling
    // VIOLATION 8: Inconsistent return types (object vs string)
    return {
        items: x,
        total: y,
        names: z
    };
}

// VIOLATION 9: Global variables
var globalCache = {};
var currentUser = null;

// VIOLATION 10: Function doing too many things (violation of SRP)
function handleUserAction(u, act, p) {
    // VIOLATION 11: No input validation
    
    // VIOLATION 12: Mixing concerns (DB, business logic, UI)
    let db = connectToDatabase();
    let userData = db.query("SELECT * FROM users WHERE id = " + u);
    
    // VIOLATION 13: Hard-coded values
    if (act == "purchase") {
        let price = 99.99;  // Where does this come from?
        
        // VIOLATION 14: Deeply nested logic
        if (userData.balance >= price) {
            if (userData.status == "active") {
                if (p != null) {
                    if (p.code != "") {
                        // Apply discount
                        price = price * 0.9;
                    }
                }
                userData.balance -= price;
                db.update(userData);
                sendEmail(userData.email, "Purchase complete");
                return true;
            }
        }
    }
    
    // VIOLATION 15: Unclear else branch
    return false;
}

// VIOLATION 16: No JSDoc comments explaining parameters/returns
// VIOLATION 17: Inconsistent formatting and indentation
function   fmt(   data   ){
let r={};
    for(let k in data){
r[k]=data[k].toString();
    }
return r;
}

// VIOLATION 18: Using var instead of const/let
var API_KEY = "sk_live_123456789";  // VIOLATION 19: Hard-coded secret!

// VIOLATION 20: Callback hell (could use async/await)
function fetchData(id, callback) {
    getUser(id, function(user) {
        getOrders(user.id, function(orders) {
            getDetails(orders[0].id, function(details) {
                callback(details);
            });
        });
    });
}

// VIOLATION 21: No module system (should use ES6 imports/exports)
// VIOLATION 22: Mixing single and double quotes
// VIOLATION 23: No semicolons (inconsistent style)

// Test code
console.log("Running best practice violation examples...")

let testData = [
    {a: true, s: 75, t: "premium", name: "Alice"},
    {a: true, s: 30, t: "basic", name: "Bob"},
    {a: false, s: 100, t: "premium", name: "Charlie"}
]

let result = proc(testData)
console.log(result)

console.log("\n" + "=".repeat(50))
console.log("VERIFICATION TASK:")
console.log("1. List all naming convention violations")
console.log("2. Identify magic numbers and hard-coded values")
console.log("3. Find violations of Single Responsibility Principle")
console.log("4. What modern JavaScript features should be used?")
console.log("5. How can the code be refactored for clarity?")
console.log("6. What security issues exist (hard-coded secrets)?")
console.log("7. How would you improve error handling?")
console.log("\nBest Practices Checklist:")
console.log("- [ ] Descriptive naming")
console.log("- [ ] Const/let instead of var")
console.log("- [ ] Template literals")
console.log("- [ ] Arrow functions")
console.log("- [ ] Async/await")
console.log("- [ ] JSDoc comments")
console.log("- [ ] Input validation")
console.log("- [ ] Error handling")
console.log("- [ ] No hard-coded secrets")
console.log("- [ ] Single Responsibility Principle")
