"""
AI-Generated Code Sample with Correctness Issue

Problem: Implement a function to calculate the median of a list of numbers.

This code was generated by an AI assistant but contains a fundamental
correctness error in the algorithm.
"""

def calculate_median(numbers):
    """
    Calculate the median value of a list of numbers.
    
    The median is the middle value when the numbers are sorted.
    For even-length lists, it's the average of the two middle values.
    
    Args:
        numbers: List of numeric values
        
    Returns:
        The median value as a float
        
    Examples:
        >>> calculate_median([1, 2, 3, 4, 5])
        3.0
        >>> calculate_median([1, 2, 3, 4])
        2.5
    """
    if not numbers:
        return None
    
    # Sort the numbers
    sorted_nums = sorted(numbers)
    n = len(sorted_nums)
    
    # CORRECTNESS ISSUE: This algorithm is fundamentally wrong
    # It always returns the average of first and last element,
    # completely ignoring the middle value(s)
    
    # Calculate "median" as average of first and last (WRONG!)
    median = (sorted_nums[0] + sorted_nums[-1]) / 2
    
    return median


# Test cases to reveal the issue
if __name__ == "__main__":
    # Test 1: Odd number of elements
    test1 = [1, 2, 3, 4, 5]
    result1 = calculate_median(test1)
    print(f"Median of {test1}: {result1}")
    print(f"Expected: 3.0, Got: {result1}, Correct: {result1 == 3.0}")
    
    # Test 2: Even number of elements
    test2 = [1, 2, 3, 4]
    result2 = calculate_median(test2)
    print(f"\nMedian of {test2}: {result2}")
    print(f"Expected: 2.5, Got: {result2}, Correct: {result2 == 2.5}")
    
    # Test 3: Unsorted input
    test3 = [5, 1, 4, 2, 3]
    result3 = calculate_median(test3)
    print(f"\nMedian of {test3}: {result3}")
    print(f"Expected: 3.0, Got: {result3}, Correct: {result3 == 3.0}")
    
    # Test 4: Duplicate values
    test4 = [1, 2, 2, 2, 3]
    result4 = calculate_median(test4)
    print(f"\nMedian of {test4}: {result4}")
    print(f"Expected: 2.0, Got: {result4}, Correct: {result4 == 2.0}")

    print("\n" + "="*50)
    print("VERIFICATION TASK:")
    print("1. What is the fundamental correctness issue?")
    print("2. What algorithm is actually implemented?")
    print("3. How should median calculation work correctly?")
