"""
AI-Generated Code Sample with Dependency Hallucination

Problem: Generate a data report with charts and export to PDF.

This code was generated by an AI assistant but references nonexistent
packages and APIs that sound plausible but don't actually exist.
"""

# HALLUCINATION 1: 'dataforge' package doesn't exist
# AI mixed up pandas with a fictional package name
from dataforge import DataFrame, DataProcessor

# HALLUCINATION 2: 'chartify' doesn't exist as a standalone package
# AI may have confused this with plotly, matplotlib, or seaborn
from chartify import BarChart, LineChart, PieChart

# HALLUCINATION 3: 'pdfmagic' is not a real package
# AI invented this instead of using reportlab or fpdf
from pdfmagic import PDFBuilder, PageLayout

# HALLUCINATION 4: Real package, but wrong API
# requests exists, but doesn't have 'fetch_json' method
import requests

def generate_report(data_source_url):
    """
    Generate a comprehensive data report with visualizations and export to PDF.
    
    Args:
        data_source_url: URL to fetch data from
        
    Returns:
        Path to generated PDF file
    """
    # HALLUCINATION 5: requests.fetch_json() doesn't exist
    # Should use requests.get().json()
    data = requests.fetch_json(data_source_url)
    
    # HALLUCINATION 6: DataProcessor.from_api() doesn't exist
    # This API is invented
    processor = DataProcessor.from_api(data)
    
    # HALLUCINATION 7: .aggregate_by_category() is not a real method
    summary = processor.aggregate_by_category(
        category='sales',
        metrics=['total', 'average', 'count']
    )
    
    # Create visualizations
    # HALLUCINATION 8: BarChart.create_from_dataframe() doesn't exist
    bar_chart = BarChart.create_from_dataframe(
        summary,
        x='category',
        y='total',
        title='Sales by Category'
    )
    
    # HALLUCINATION 9: LineChart.with_trend_line() is not real
    line_chart = LineChart.with_trend_line(
        summary,
        x='date',
        y='total',
        show_confidence_interval=True
    )
    
    # HALLUCINATION 10: PieChart.auto_explode() doesn't exist
    pie_chart = PieChart.auto_explode(
        summary,
        values='total',
        labels='category',
        explode_largest=True
    )
    
    # Build PDF
    # HALLUCINATION 11: PDFBuilder and its methods are invented
    pdf = PDFBuilder(layout=PageLayout.PORTRAIT)
    pdf.add_title("Sales Report", font_size=24)
    pdf.add_chart(bar_chart, position='top')
    pdf.add_chart(line_chart, position='middle')
    pdf.add_chart(pie_chart, position='bottom')
    
    # HALLUCINATION 12: .export_with_watermark() doesn't exist
    output_path = pdf.export_with_watermark(
        filename='sales_report.pdf',
        watermark='CONFIDENTIAL'
    )
    
    return output_path


def analyze_sentiment(text_data):
    """
    Perform sentiment analysis on text data.
    """
    # HALLUCINATION 13: 'nlpkit' package doesn't exist
    # AI confused this with nltk, spacy, or textblob
    from nlpkit import SentimentAnalyzer
    
    # HALLUCINATION 14: .analyze_batch() with auto_language_detect doesn't exist
    analyzer = SentimentAnalyzer(model='advanced-v2')
    results = analyzer.analyze_batch(
        text_data,
        auto_language_detect=True,
        return_confidence_scores=True
    )
    
    return results


# Demonstration
if __name__ == "__main__":
    print("DEPENDENCY HALLUCINATION DEMONSTRATION")
    print("="*50)
    
    print("\nAttempting to run hallucinated code...")
    print("(This will fail with ImportError)")
    
    try:
        result = generate_report("https://api.example.com/sales")
        print(f"Success: {result}")
    except ImportError as e:
        print(f"\nImportError: {e}")
        print("^ These packages don't exist!")
    except AttributeError as e:
        print(f"\nAttributeError: {e}")
        print("^ These API methods don't exist!")
    
    print("\n" + "="*50)
    print("VERIFICATION TASK:")
    print("1. List all hallucinated package names")
    print("2. Check PyPI (https://pypi.org) for each package")
    print("3. Identify hallucinated API methods in real packages")
    print("4. What are the correct alternative packages?")
    print("   - For data: pandas, numpy")
    print("   - For charts: matplotlib, plotly, seaborn")
    print("   - For PDF: reportlab, fpdf2, weasyprint")
    print("   - For requests: requests.get().json()")
    print("   - For NLP: nltk, spacy, textblob, transformers")
    print("\n5. How can you verify packages exist before using them?")
    print("   - Search PyPI: https://pypi.org")
    print("   - Check documentation")
    print("   - Try: pip search <package> (deprecated)")
    print("   - Try: pip install --dry-run <package>")
