"""
AI-Generated Code Sample with Logic Error

Problem: Validate password strength based on security requirements.

This code was generated by an AI assistant but contains edge case
handling issues and boundary condition bugs.
"""

def validate_password(password):
    """
    Validate password meets security requirements:
    - At least 8 characters long
    - Contains at least one uppercase letter
    - Contains at least one lowercase letter
    - Contains at least one digit
    - Contains at least one special character (!@#$%^&*)
    
    Args:
        password: String password to validate
        
    Returns:
        Boolean: True if valid, False otherwise
        
    Examples:
        >>> validate_password("SecurePass1!")
        True
        >>> validate_password("weak")
        False
    """
    # LOGIC ERROR 1: No null/None check - will crash on None input
    # if password is None:
    #     return False
    
    # LOGIC ERROR 2: Off-by-one error - requires > 8 instead of >= 8
    if len(password) > 8:  # WRONG: Should be >= 8
        return False
    
    # Check for uppercase letter
    has_upper = False
    for char in password:
        if char.isupper():
            has_upper = True
            break
    
    # Check for lowercase letter
    has_lower = False
    for char in password:
        if char.islower():
            has_lower = True
            break
    
    # Check for digit
    has_digit = False
    for char in password:
        if char.isdigit():
            has_digit = True
            break
    
    # LOGIC ERROR 3: Missing check for special characters
    # The requirement states special characters are needed,
    # but there's no validation for them
    
    # LOGIC ERROR 4: Incorrect boolean logic - returns True when invalid
    # Should return True if ALL conditions met, but logic is inverted
    return not (has_upper and has_lower and has_digit)


# Test cases to reveal the issues
if __name__ == "__main__":
    # Test 1: Valid password (exactly 8 chars)
    test1 = "Pass123!"
    result1 = validate_password(test1)
    print(f"Password '{test1}' valid: {result1}")
    print(f"Expected: True, Got: {result1}")
    
    # Test 2: Valid password (9 chars)
    test2 = "Pass1234!"
    result2 = validate_password(test2)
    print(f"\nPassword '{test2}' valid: {result2}")
    print(f"Expected: True, Got: {result2}")
    
    # Test 3: Too short
    test3 = "Pass1!"
    result3 = validate_password(test3)
    print(f"\nPassword '{test3}' valid: {result3}")
    print(f"Expected: False, Got: {result3}")
    
    # Test 4: Missing special character
    test4 = "Password123"
    result4 = validate_password(test4)
    print(f"\nPassword '{test4}' valid: {result4}")
    print(f"Expected: False, Got: {result4}")
    
    # Test 5: Empty string edge case
    test5 = ""
    try:
        result5 = validate_password(test5)
        print(f"\nPassword '' valid: {result5}")
        print(f"Expected: False, Got: {result5}")
    except Exception as e:
        print(f"\nEmpty string caused error: {e}")
    
    # Test 6: None edge case
    test6 = None
    try:
        result6 = validate_password(test6)
        print(f"\nPassword None valid: {result6}")
        print(f"Expected: False, Got: {result6}")
    except Exception as e:
        print(f"\nNone input caused error: {e}")

    print("\n" + "="*50)
    print("VERIFICATION TASK:")
    print("1. What edge cases are not handled?")
    print("2. Find the off-by-one error")
    print("3. What requirement is missing from validation?")
    print("4. Is the boolean logic correct?")
