name: Deploy Docs to GitHub Pages

on:
  workflow_run:
    workflows: ["CI"] # This must match the exact name from build.yml
    types:
      - completed
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # Only run if the build workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Get the commit that triggered the original workflow
          ref: ${{ github.event.workflow_run.head_sha }}
      
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts # Must match artifact name from build.yml
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
