
name: Deploy

on:
  workflow_run:
    workflows: ["CI"] # This must match the exact name from ci.yml
    types:
      - completed
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read # Needed to download artifacts

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # Only run if the build workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download artifacts from CI workflow
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Display structure of downloaded files
        run: ls -lR

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: .
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4